import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CleanWaterModel(props) {
  const { nodes, materials } = useGLTF(
    "models/quizBiodiversity/CleanWaterModel.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Плоскость.geometry}
        material={materials["Material.008"]}
        position={[-5.482, 0.285, 3.838]}
        scale={0.174}
      />
      <group
        position={[-2.08, 1.944, -1.321]}
        rotation={[Math.PI / 2, 0, 0.373]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh_1.geometry}
          material={materials.DoryBlue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh_2.geometry}
          material={materials.DoryYellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh_3.geometry}
          material={materials.DoryBlack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh_4.geometry}
          material={materials.Fish}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh_5.geometry}
          material={materials.FishUnderside}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh_6.geometry}
          material={materials.ClownFishOrange}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh_7.geometry}
          material={materials.ClownFishWhite}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh_8.geometry}
          material={materials.ClownFishBlack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh_9.geometry}
          material={materials.BrownFish}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh_10.geometry}
          material={materials.RedPart}
        />
      </group>
      <group
        position={[7.133, 2.2, -11.223]}
        rotation={[Math.PI / 2, 0, -0.274]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tuna_TunaMesh001_1.geometry}
          material={materials["Fish.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tuna_TunaMesh001_2.geometry}
          material={materials["FishUnderside.001"]}
        />
      </group>
      <group
        position={[8.072, 2.872, -9.246]}
        rotation={[Math.PI / 2, 0, -0.274]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh001_1.geometry}
          material={materials["DoryBlue.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh001_2.geometry}
          material={materials["DoryYellow.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh001_3.geometry}
          material={materials["DoryBlack.001"]}
        />
      </group>
      <group
        position={[8.25, 2.11, -10.207]}
        rotation={[Math.PI / 2, 0, -0.274]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClownFish_ClownFishMesh001_1.geometry}
          material={materials["ClownFishOrange.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClownFish_ClownFishMesh001_2.geometry}
          material={materials["ClownFishWhite.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClownFish_ClownFishMesh001_3.geometry}
          material={materials["ClownFishBlack.001"]}
        />
      </group>
      <group
        position={[6.208, 3.243, -11.65]}
        rotation={[Math.PI / 2, 0, -0.274]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Carp_CarpMesh001_1.geometry}
          material={materials["BrownFish.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Carp_CarpMesh001_2.geometry}
          material={materials["RedPart.001"]}
        />
      </group>
      <group
        position={[-7.244, 2.793, -7.966]}
        rotation={[Math.PI / 2, 0, 0.656]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh002_1.geometry}
          material={materials["DoryBlue.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh002_2.geometry}
          material={materials["DoryYellow.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh002_3.geometry}
          material={materials["DoryBlack.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh002_4.geometry}
          material={materials["Fish.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh002_5.geometry}
          material={materials["FishUnderside.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh002_6.geometry}
          material={materials["ClownFishOrange.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh002_7.geometry}
          material={materials["ClownFishWhite.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh002_8.geometry}
          material={materials["ClownFishBlack.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh002_9.geometry}
          material={materials["BrownFish.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh002_10.geometry}
          material={materials["RedPart.002"]}
        />
      </group>
      <group
        position={[-7.707, 2.437, 7.318]}
        rotation={[Math.PI / 2, 0, -0.612]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh003_1.geometry}
          material={materials["DoryBlue.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh003_2.geometry}
          material={materials["DoryYellow.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh003_3.geometry}
          material={materials["DoryBlack.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh003_4.geometry}
          material={materials["Fish.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh003_5.geometry}
          material={materials["FishUnderside.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh003_6.geometry}
          material={materials["ClownFishOrange.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh003_7.geometry}
          material={materials["ClownFishWhite.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh003_8.geometry}
          material={materials["ClownFishBlack.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh003_9.geometry}
          material={materials["BrownFish.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh003_10.geometry}
          material={materials["RedPart.003"]}
        />
      </group>
      <group
        position={[-5.385, 2.003, -3.044]}
        rotation={[Math.PI / 2, 0, -0.812]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh004_1.geometry}
          material={materials["DoryBlue.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh004_2.geometry}
          material={materials["DoryYellow.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh004_3.geometry}
          material={materials["DoryBlack.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh004_4.geometry}
          material={materials["Fish.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh004_5.geometry}
          material={materials["FishUnderside.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh004_6.geometry}
          material={materials["ClownFishOrange.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh004_7.geometry}
          material={materials["ClownFishWhite.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh004_8.geometry}
          material={materials["ClownFishBlack.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh004_9.geometry}
          material={materials["BrownFish.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh004_10.geometry}
          material={materials["RedPart.004"]}
        />
      </group>
      <group
        position={[-3.165, 3.187, 4.123]}
        rotation={[Math.PI / 2, 0, 0.409]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh005_1.geometry}
          material={materials["DoryBlue.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh005_2.geometry}
          material={materials["DoryYellow.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh005_3.geometry}
          material={materials["DoryBlack.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh005_4.geometry}
          material={materials["Fish.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh005_5.geometry}
          material={materials["FishUnderside.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh005_6.geometry}
          material={materials["ClownFishOrange.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh005_7.geometry}
          material={materials["ClownFishWhite.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh005_8.geometry}
          material={materials["ClownFishBlack.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh005_9.geometry}
          material={materials["BrownFish.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh005_10.geometry}
          material={materials["RedPart.005"]}
        />
      </group>
      <group
        position={[-1.482, 3.306, -7.284]}
        rotation={[Math.PI / 2, 0, 0.591]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh006_1.geometry}
          material={materials["DoryBlue.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh006_2.geometry}
          material={materials["DoryYellow.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh006_3.geometry}
          material={materials["DoryBlack.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh006_4.geometry}
          material={materials["Fish.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh006_5.geometry}
          material={materials["FishUnderside.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh006_6.geometry}
          material={materials["ClownFishOrange.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh006_7.geometry}
          material={materials["ClownFishWhite.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh006_8.geometry}
          material={materials["ClownFishBlack.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh006_9.geometry}
          material={materials["BrownFish.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh006_10.geometry}
          material={materials["RedPart.006"]}
        />
      </group>
      <group
        position={[4.295, 2.951, -5.173]}
        rotation={[Math.PI / 2, 0, -0.359]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh007_1.geometry}
          material={materials["DoryBlue.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh007_2.geometry}
          material={materials["DoryYellow.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh007_3.geometry}
          material={materials["DoryBlack.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh007_4.geometry}
          material={materials["Fish.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh007_5.geometry}
          material={materials["FishUnderside.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh007_6.geometry}
          material={materials["ClownFishOrange.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh007_7.geometry}
          material={materials["ClownFishWhite.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh007_8.geometry}
          material={materials["ClownFishBlack.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh007_9.geometry}
          material={materials["BrownFish.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh007_10.geometry}
          material={materials["RedPart.007"]}
        />
      </group>
      <group position={[8.98, 2.872, 6.464]} rotation={[Math.PI / 2, 0, 0.581]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh008_1.geometry}
          material={materials["DoryBlue.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh008_2.geometry}
          material={materials["DoryYellow.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh008_3.geometry}
          material={materials["DoryBlack.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh008_4.geometry}
          material={materials["Fish.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh008_5.geometry}
          material={materials["FishUnderside.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh008_6.geometry}
          material={materials["ClownFishOrange.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh008_7.geometry}
          material={materials["ClownFishWhite.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh008_8.geometry}
          material={materials["ClownFishBlack.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh008_9.geometry}
          material={materials["BrownFish.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh008_10.geometry}
          material={materials["RedPart.008"]}
        />
      </group>
      <group
        position={[5.312, 1.924, 1.108]}
        rotation={[Math.PI / 2, 0, 0.337]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh009_1.geometry}
          material={materials["DoryBlue.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh009_2.geometry}
          material={materials["DoryYellow.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh009_3.geometry}
          material={materials["DoryBlack.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh009_4.geometry}
          material={materials["Fish.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh009_5.geometry}
          material={materials["FishUnderside.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh009_6.geometry}
          material={materials["ClownFishOrange.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh009_7.geometry}
          material={materials["ClownFishWhite.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh009_8.geometry}
          material={materials["ClownFishBlack.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh009_9.geometry}
          material={materials["BrownFish.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh009_10.geometry}
          material={materials["RedPart.009"]}
        />
      </group>
      <group
        position={[1.892, 2.872, -10.154]}
        rotation={[Math.PI / 2, 0, -0.326]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh010_1.geometry}
          material={materials["DoryBlue.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh010_2.geometry}
          material={materials["DoryYellow.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh010_3.geometry}
          material={materials["DoryBlack.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh010_4.geometry}
          material={materials["Fish.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh010_5.geometry}
          material={materials["FishUnderside.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh010_6.geometry}
          material={materials["ClownFishOrange.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh010_7.geometry}
          material={materials["ClownFishWhite.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh010_8.geometry}
          material={materials["ClownFishBlack.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh010_9.geometry}
          material={materials["BrownFish.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh010_10.geometry}
          material={materials["RedPart.010"]}
        />
      </group>
      <group
        position={[4.57, 2.181, 3.696]}
        rotation={[Math.PI / 2, 0, -0.802]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh011_1.geometry}
          material={materials["DoryBlue.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh011_2.geometry}
          material={materials["DoryYellow.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh011_3.geometry}
          material={materials["DoryBlack.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh011_4.geometry}
          material={materials["Fish.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh011_5.geometry}
          material={materials["FishUnderside.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh011_6.geometry}
          material={materials["ClownFishOrange.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh011_7.geometry}
          material={materials["ClownFishWhite.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh011_8.geometry}
          material={materials["ClownFishBlack.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh011_9.geometry}
          material={materials["BrownFish.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh011_10.geometry}
          material={materials["RedPart.011"]}
        />
      </group>
      <group
        position={[0.329, 1.707, 8.267]}
        rotation={[Math.PI / 2, 0, 0.655]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh012_1.geometry}
          material={materials["DoryBlue.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh012_2.geometry}
          material={materials["DoryYellow.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh012_3.geometry}
          material={materials["DoryBlack.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh012_4.geometry}
          material={materials["Fish.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh012_5.geometry}
          material={materials["FishUnderside.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh012_6.geometry}
          material={materials["ClownFishOrange.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh012_7.geometry}
          material={materials["ClownFishWhite.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh012_8.geometry}
          material={materials["ClownFishBlack.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh012_9.geometry}
          material={materials["BrownFish.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh012_10.geometry}
          material={materials["RedPart.012"]}
        />
      </group>
      <group
        position={[-3.475, 1.865, -8.789]}
        rotation={[Math.PI / 2, 0, -0.12]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh013_1.geometry}
          material={materials["DoryBlue.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh013_2.geometry}
          material={materials["DoryYellow.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh013_3.geometry}
          material={materials["DoryBlack.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh013_4.geometry}
          material={materials["Fish.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh013_5.geometry}
          material={materials["FishUnderside.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh013_6.geometry}
          material={materials["ClownFishOrange.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh013_7.geometry}
          material={materials["ClownFishWhite.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh013_8.geometry}
          material={materials["ClownFishBlack.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh013_9.geometry}
          material={materials["BrownFish.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh013_10.geometry}
          material={materials["RedPart.013"]}
        />
      </group>
      <group
        position={[8.669, 2.042, -4.041]}
        rotation={[Math.PI / 2, 0, 0.236]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh014_1.geometry}
          material={materials["DoryBlue.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh014_2.geometry}
          material={materials["DoryYellow.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh014_3.geometry}
          material={materials["DoryBlack.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh014_4.geometry}
          material={materials["Fish.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh014_5.geometry}
          material={materials["FishUnderside.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh014_6.geometry}
          material={materials["ClownFishOrange.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh014_7.geometry}
          material={materials["ClownFishWhite.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh014_8.geometry}
          material={materials["ClownFishBlack.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh014_9.geometry}
          material={materials["BrownFish.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh014_10.geometry}
          material={materials["RedPart.014"]}
        />
      </group>
      <group position={[7.742, 2.891, 2.673]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh015_1.geometry}
          material={materials["DoryBlue.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh015_2.geometry}
          material={materials["DoryYellow.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh015_3.geometry}
          material={materials["DoryBlack.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh015_4.geometry}
          material={materials["Fish.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh015_5.geometry}
          material={materials["FishUnderside.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh015_6.geometry}
          material={materials["ClownFishOrange.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh015_7.geometry}
          material={materials["ClownFishWhite.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh015_8.geometry}
          material={materials["ClownFishBlack.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh015_9.geometry}
          material={materials["BrownFish.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh015_10.geometry}
          material={materials["RedPart.015"]}
        />
      </group>
      <group
        position={[-5.897, 2.003, 1.522]}
        rotation={[Math.PI / 2, 0, -1.45]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh016_1.geometry}
          material={materials["DoryBlue.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh016_2.geometry}
          material={materials["DoryYellow.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh016_3.geometry}
          material={materials["DoryBlack.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh016_4.geometry}
          material={materials["Fish.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh016_5.geometry}
          material={materials["FishUnderside.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh016_6.geometry}
          material={materials["ClownFishOrange.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh016_7.geometry}
          material={materials["ClownFishWhite.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh016_8.geometry}
          material={materials["ClownFishBlack.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh016_9.geometry}
          material={materials["BrownFish.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh016_10.geometry}
          material={materials["RedPart.016"]}
        />
      </group>
      <group
        position={[1.935, 3.653, -2.673]}
        rotation={[Math.PI / 2, 0, -2.458]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh017_1.geometry}
          material={materials["DoryBlue.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh017_2.geometry}
          material={materials["DoryYellow.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh017_3.geometry}
          material={materials["DoryBlack.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh017_4.geometry}
          material={materials["Fish.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh017_5.geometry}
          material={materials["FishUnderside.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh017_6.geometry}
          material={materials["ClownFishOrange.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh017_7.geometry}
          material={materials["ClownFishWhite.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh017_8.geometry}
          material={materials["ClownFishBlack.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh017_9.geometry}
          material={materials["BrownFish.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dory_DoryMesh017_10.geometry}
          material={materials["RedPart.017"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.uploads_files_3977413_珊瑚.geometry}
        material={materials.Material}
        position={[-0.542, 1.562, -11.165]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.016}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.uploads_files_3977413_珊瑚001.geometry}
        material={materials["Material.002"]}
        position={[-3.203, 1.562, -6.416]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.016}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.uploads_files_3977413_珊瑚002.geometry}
        material={materials["Material.009"]}
        position={[-0.42, 1.562, -1.381]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.016}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.uploads_files_3977413_珊瑚003.geometry}
        material={materials["Material.023"]}
        position={[-0.87, 1.562, -12.107]}
        rotation={[Math.PI / 2, 0, 2.652]}
        scale={0.016}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.uploads_files_3977413_珊瑚004.geometry}
        material={materials["Material.024"]}
        position={[-7.87, 1.562, -0.89]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.016}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.uploads_files_3977413_珊瑚005.geometry}
        material={materials["Material.025"]}
        position={[5.68, 1.562, 5.087]}
        rotation={[Math.PI / 2, 0, 2.96]}
        scale={0.016}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.uploads_files_3977413_珊瑚006.geometry}
        material={materials["Material.026"]}
        position={[1.791, 1.562, -7.235]}
        rotation={[Math.PI / 2, 0, 2.376]}
        scale={0.016}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.uploads_files_3977413_珊瑚007.geometry}
        material={materials["Material.027"]}
        position={[-1.975, 1.562, 5.25]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.016}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.uploads_files_3977413_珊瑚008.geometry}
        material={materials["Material.028"]}
        position={[-10.899, 1.562, -11.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.016}
      />
    </group>
  );
}

useGLTF.preload("/CleanWaterModel.glb");
